cargo-features = ["edition2021"]

[workspace]

members = [
    "home",
    "replica",
    "updater-manager",
    "nomad-base",
    "ownable",
    "queue",
    "merkle",
    "lib",
    "test-utils",
]
