cargo-features = ["edition2021"]

[workspace]

members = [
    "common",
    "test-utils",
    "contracts/home",
    "contracts/replica",
    "contracts/updater-manager",
    "contracts/nomad-base",
    "contracts/ownable",
    "contracts/queue",
    "contracts/merkle",
]
